### ISSUE TITLE
Set defaults in the database

### ISSUE THREAD

**Issue by joelmellon** [glorand/laravel-model-settings#100]
**Is your feature request related to a problem? Please describe.**
Changing defaults currently requires code updates.

**Describe the solution you'd like**
It would be great to have the ability to create, edit, and even delete defaults for models directly in the database so they can be changed without performing code changes, releases, or deployments.

I think just a default_settings table would probably keep things simple, with a model_type column that associates a model with a single row. The table schema structure would pretty much look the same as the model_settings table minus the model_id column.

Thanks for the awesome package, I'm loving it so far. 🙏

**Comment by glorand** [comment]
Hey @joelmellon thanks for your idea. Maybe you can prepare a pull request with your idea.
