### ISSUE TITLE
How to get GetMultiple with different default values

### ISSUE THREAD

**Issue by pathros** [glorand/laravel-model-settings#102]
As for getting multiple settings at once, currently what is supported is
```php
//multiple
$user->settings()->getMultiple(
	[
		'some.setting_1',
		'some.setting_2',
	],
	'default value'
);
```

However, in my case, seeting_1 is true and setting_2 is false. I have tried:
```php
//multiple
$user->settings()->getMultiple(
	[
		'some.setting_1' => true,
		'some.setting_2' => false,
	],
);
```
But it doesn't work.

Any workaround???

**Comment by glorand** [comment]
@pathros In the current implementation this is not possible. But I added to the asked features list
