### ISSUE TITLE
Deprecation in Log and bug after upgrade

### ISSUE THREAD

**Issue by keyur555** [glorand/laravel-model-settings#104]
Hello,

after I upgrade to PHP 8.2 on Laravel Vapor and try use setMultiple(), it does not save the changes to the database anymore.

In the logs I can see: `Use of "parent" in callables is deprecated in /var/task/vendor/glorand/laravel-model-settings/src/Traits/HasSettings.php on line 43`

When I update my code to use settings()->set() multiple times for all of the items then it works again.

I tried to look into the code but I don't know how this can be fixed. Do you have ideas?

**Comment by jeffreyvanhees** [comment]
This is because the use  of parent in callables is deprecated in PHP 8.2:

```php
public function __call($name, $args)
    {
        if (isset($this->invokeSettingsBy) && $name === $this->invokeSettingsBy) {
            return $this->settings();
        }

        return is_callable(['parent', '__call']) ? parent::__call($name, $args) : null;   // < -----
    }
```

**Comment by glorand** [comment]
@jeffreyvanhees Thanks for the pull request: #105
