### ISSUE TITLE
Different database connection 

### ISSUE THREAD

**Issue by tiagosimoesdev** [glorand/laravel-model-settings#11]
Is it possible to use a different connection for model settings ? maybe it should use the connection that the model is using no ?

**Comment by glorand** [comment]
@tiagosimoesdev sure, just extend the ModelSettings table, and update the connection property
```php
<?php

namespace App;

use Glorand\Model\Settings\Models\ModelSettings;

class CustomModelSettings extends ModelSettings
{
    protected $connection = 'second_db_connection';
}
```

**Comment by tiagosimoesdev** [comment]
I opted to use the Settings field instead . Thanks so much for this simple and powerful package.

**Comment by glorand** [comment]
You're welcome!
