### ISSUE TITLE
Use accessor instead of method

### ISSUE THREAD

**Issue by hubertnnn** [glorand/laravel-model-settings#14]
I like the idea of settings, but looking at it, settings should be a property of model, not a method.
So the more laravel way of accessing them would be to use
`$user->settings->get('some.setting');` instead of
`$user->settings()->get('some.setting');`

You can easily do that by using an accesor in your trait:
```
    public function getSettingsAttribute()
    {
        return new FieldSettingsManager($this);
    }
```

**Comment by glorand** [comment]
Yes is true, but I have chosen function because with the current implementation the user can use custom name for the settings field (ex. `model_settings`) and in same time can have an attribute named `settings` with a totally different data.
