### ISSUE TITLE
[Proposal] No (database) query if settings are loaded

### ISSUE THREAD

**Issue by edwinvdpol** [glorand/laravel-model-settings#25]
Hi,

Is it possible, that when the settings are loaded, the current loaded settings are used instead of querying the database (if `HasSettingsTable` is used) every time the `get()` or `all()` method is used? Like, it remembers the loaded settings and uses those if available.

This would save a lot of (database) queries.

Now, I pass the result of the `all()` method from the controllers in the views.

-- Edwin

**Comment by glorand** [comment]
Done by PR #28
