### ISSUE TITLE
Unknown field (settings) on table users

### ISSUE THREAD

**Issue by chadidi** [glorand/laravel-model-settings#31]
I sometimes get this error, even though I have the field on my users table.

**Comment by glorand** [comment]
Can you paste here the complete trace, from the log file.

**Comment by LaPelle** [comment]
I am getting this error as well in a feature test in the PHPUnit setUp method. I create a new user by using a factory that is not filling the settings field, leaving the column ``null``.   

A middleware checks to set the localization and timezone for the user falling back to the ``defaultSettings``. This works correctly when manually testing, but not in my feature test where it throws:

````php
{#1521
  +"message": "Unknown field (settings) on table users"
  +"exception": "Glorand\Model\Settings\Exceptions\ModelSettingsException"
  +"file": "/application/vendor/glorand/laravel-model-settings/src/Traits/HasSettingsField.php"
  +"line": 59
  +"trace": array:54 [
    0 => {#1536
      +"file": "/application/vendor/glorand/laravel-model-settings/src/Managers/AbstractSettingsManager.php"
      +"line": 41
      +"function": "getSettingsValue"
      +"class": "App\Models\User"
      +"type": "->"
    }
    1 => {#1538
      +"file": "/application/vendor/glorand/laravel-model-settings/src/Managers/AbstractSettingsManager.php"
      +"line": 60
      +"function": "all"
      +"class": "Glorand\Model\Settings\Managers\AbstractSettingsManager"
      +"type": "->"
    }
    2 => {#1524
      +"file": "/application/app/Http/Middleware/SetLocalizaton.php"
      +"line": 25
      +"function": "get"
      +"class": "Glorand\Model\Settings\Managers\AbstractSettingsManager"
      +"type": "->"
    }
    3 => {#1537
      +"file": "/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "App\Http\Middleware\SetLocalizaton"
      +"type": "->"
    }
}
````

**Note**: I am using ``RefreshDatabase``

**Comment by chadidi** [comment]
the problem is with Larave Model `getAttributes` method it doesn't get settings column so your condition will always fail.

https://github.com/glorand/laravel-model-settings/blob/79a2f0a0a77da6994607f49b90d33da31d1524d3/src/Traits/HasSettingsField.php#L42

**Comment by LaPelle** [comment]
I can confirm that adding the settings field to my User Factory fixed this issue, but I don't know if @chadidi has the same problem.

**Comment by chadidi** [comment]
@LaPelle yes, will work when you set the field, but it should work in the other case too! the way I did it is by overriding HasSettingsField.php trait and removing that check maybe later I may add some line to check if the column exists directly on the database table.

Have a nice day too 👍

**Comment by LaPelle** [comment]
I see mixed up your names, I though the reply was from @glorand. But I agree, it should work either way.

**Comment by glorand** [comment]
@chadidi and @LaPelle, think this PR #32 will fix this issue

**Comment by chadidi** [comment]
Thanks, @glorand

I will test this next Monday and let you know,

**Comment by SDCCardsDeveloper** [comment]
Hi,

I still have this error "Unknown field (settings) on table members". The field settings exist on the table members.

if I remove this code in Glorand\Model\Settings\Traits\HasSettingsField
```
if (!$this->hasSettingsField()) {
throw new ModelSettingsException("Unknown field ($settingsFieldName) on table {$this->getTable()}");
 }
``` 
it will work fine.
I am using laravel 6.9.0 and this package version 3.5.4.
