### ISSUE TITLE
Maximum function nesting level of '512' reached, aborting!

### ISSUE THREAD

**Issue by chadidi** [glorand/laravel-model-settings#39]
My question is what is the best way to return settings field with default settings without creating a new attribute?

**Comment by chadidi** [comment]
I suggest something like:
```
static::retrieved(function (self $model) {
	if(config('model_settings.load_settings_when_retrieved')) {
    	$model->settings = $model->settings()->all();
	}
});
```

**Comment by glorand** [comment]
@chadidi - not a bad idea, but I want to maintain the settings attribute on model clean (contain only data from DB field/table), maybe you can create a pull request and we can start a discussion based on code.
