### ISSUE TITLE
Unknown field (settings)

### ISSUE THREAD

**Issue by SDCCardsDeveloper** [glorand/laravel-model-settings#43]
Hi,

I'm having this issue "Unknown field (settings) on table members". The field settings exist on the table members.

if I remove this code in Glorand\Model\Settings\Traits\HasSettingsField
```
if (!$this->hasSettingsField()) {
throw new ModelSettingsException("Unknown field ($settingsFieldName) on table {$this->getTable()}");
 }
``` 
it will work fine.
I am using laravel 6.9.0 and this package version 3.5.4.

Anyone has this issue?

**Comment by bagaskarawg** [comment]
If you look at the `hasSettingsField` method, you will see it like so:
```
    /**
     * @return mixed
     * @throws \Glorand\Model\Settings\Exceptions\ModelSettingsException
     */
    private function hasSettingsField()
    {
        try {
            return cache()->remember(
                config('model_settings.settings_table_cache_prefix') . '::has_field',
                now()->addDays(1),
                function () {
                    return Schema::hasColumn($this->getTable(), $this->getSettingsFieldName());
                }
            );
        } catch (\Exception $e) {
            throw new ModelSettingsException("Cache: " . $e->getMessage());
        }
    }
```

I have run into the same issue and I try to clear the cache after looking at the source and all you need to do is run `php artisan cache:clear`, maybe it is used for performance in production environment.

**Comment by glorand** [comment]
@SDCCardsDeveloper can you confirm that cleaning the cahe  (`php artisan cache:clear`) fixes the issue?

**Comment by SDCCardsDeveloper** [comment]
Hi @glorand @bagaskarawg 

I've executed ```php artisan cache:clear``` and tried again but the same error result.

**Comment by anthonytp** [comment]
I had the same error:

> ModelSettingsException with message 'Unknown field (settings) on table Users

Clearing the cache worked for me. 👍

**Comment by glorand** [comment]
close due to inactivity

**Comment by SDCCardsDeveloper** [comment]
I am still having this issue until this now. clearing cache does not solve this issue.

**Comment by glorand** [comment]
> I am still having this issue until this now. clearing cache does not solve this issue.

Please update to the latest version

**Comment by SDCCardsDeveloper** [comment]
> > I am still having this issue until this now. clearing cache does not solve this issue.
> 
> Please update to the latest version
@glorand 
I just updated to last version and the issue seems fixed. Thank you

**Comment by tiagosimoesdev** [comment]
I have updated to the latest version ( 3.6.5 ) and php artisan cache:clear , but I still have the same error :(

Exception Message:↵↵Unknown field (extra) on table roles

**Comment by ametad** [comment]
In version 3.6.5 I also have this error:

`Glorand/Model/Settings/Exceptions/ModelSettingsException with message 'Unknown field (settings) on table companies'`

And my co-workers as well... The only thing that really helps is remove- and require again with composer....

I will update this package now and get back with feedback if that solved my problem.

**Comment by ametad** [comment]
In version **3.6.7** I got the same error. But I now have a clue on what could be wrong: the model has a non-default database connection. My project has multiple database connection, hence.

This code from `\Glorand\Model\Settings\Traits\HasSettingsField::hasSettingsField`, does not take into account different database connections:

```php
Schema::hasColumn($this->getTable(), $this->getSettingsFieldName());
```

Good thing that the `Schema` facade has a method that allows connections, this could be the solution:

```php
    /**
     * @return mixed
     */
    private function hasSettingsField()
    {
        return Cache::remember(
            config('model_settings.settings_table_cache_prefix') . '::has_field',
            now()->addDays(1),
            function () {
                return Schema::connection($this->getConnectionName())->hasColumn($this->getTable(), $this->getSettingsFieldName());
            }
        );
    }
```

Do not forget to clear your cache (again).
