### ISSUE TITLE
JSON DataType not supported with MariaDB ?

### ISSUE THREAD

**Issue by AntonLugtenburg** [glorand/laravel-model-settings#47]
`[Illuminate\Database\QueryException]
 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
 n your SQL syntax; check the manual that corresponds to your MariaDB server
  version for the right syntax to use near 'json not null, `description` jso
 n null, `details` json null, `features` json nul' at line 1 (SQL: create ta
 ble `products` (`id` int unsigned not null auto_increment primary key, `nam
 e` json not null, `description` json null, `details` json null, `features`
 json null, `price` int not null, `category_id` int not null, `extras` json
 null, `created_at` timestamp null, `updated_at` timestamp null) default cha
 racter set utf8 collate utf8_unicode_ci)`

Unfortunately MariaDB doesn't support column type of json :/. I changed to longText to make it work. But is that in all cases safe to do ?

**Comment by joveice** [comment]
MariaDB supports JSON, but Laravel does not support MariaDB. This makes that work https://github.com/ybr-nx/laravel-mariadb.
I don't know if the text field would make any issues or such.

**Comment by glorand** [comment]
@AntonLugtenburg please use the mentioned package by @joveice  [laravel-mariadb](https://github.com/ybr-nx/laravel-mariadb)  - which add MariaDB JSON support to Laravel.
Requires at least MariaDB 10.2.7 to use ->json() migrations.

**Comment by AntonLugtenburg** [comment]
Thank you :)
