### ISSUE TITLE
[Proposal] Getting default settings from config file

### ISSUE THREAD

**Issue by RichardDern** [glorand/laravel-model-settings#52]
Hi,

It would be cleaner if default settings could be kept in a config file, pretty much like the rest of the app (ie. inside the ```config``` folder).

Alongside the ```$defaultSettings``` property, we could have a ```$defaultSettingsFromConfig``` property, which would take a string representing the dot notation to model settings.

For instance, I would declare an array in ```config/user_settings.php```, and put ```$defaultSettingsFromConfig = 'user_settings'``` in my model. Then the package would load them using ```config($model->defaultSettingsFromConfig)```.

**Comment by glorand** [comment]
@RichardDern 
I've been thinking about this a lot, do not exclude the possibility that a future release (maybe the next) will contain this possibility to get the default settings from a config file. 
The only concern now for me is the easy usability (transparency in code level) of the package.

**Comment by RichardDern** [comment]
In `src/Traits/HasSettings/php`, you could add a condition to the `if` block:

```
if (property_exists($this, 'defaultSettings')) {
    return Arr::wrap($this->defaultSettings);
} else if(property_exists($this, 'defaultSettingsFromConfig')) {
    return config($this->defaultSettingsFromConfig, []);
}
```

It feels pretty much easy to me :) Or maybe I didn't understand what you mean by "transparency in code level".
