### ISSUE TITLE
[Proposal] Remove env references for some config options

### ISSUE THREAD

**Issue by hivokas** [glorand/laravel-model-settings#65]
First of all, thanks for this great package! 

Now let me explain what I think.

Here is how the config file looks like now:

```php
return [
    'settings_field_name' => env('MODEL_SETTINGS_FIELD_NAME', 'settings'),
    'settings_table_name' => env('MODEL_SETTINGS_TABLE_NAME', 'model_settings'),
    'settings_persistent' => env('MODEL_SETTINGS_PERSISTENT', true),
    'settings_table_use_cache' => env('MODEL_SETTINGS_TABLE_USE_CACHE', true),
    'settings_table_cache_prefix' => env('MODEL_SETTINGS_TABLE_CACHE_PREFIX', 'model_settings:'),
    'defaultSettings' => [
        'users' => [

        ]
    ]
];
```

What I think about that is that we don't need to reference these env variables: `MODEL_SETTINGS_FIELD_NAME` & `MODEL_SETTINGS_TABLE_NAME`. Because these values will be the same for each environment. 

Let me explain what I mean. Let's imagine I've created one migration for the field settings and another one migration for the table settings. Field/table names will be hard-coded in these migrations. If I ever want to update these names, I'll need to create new migrations to rename table/column & update the config. I'll need these new names for ALL environments. That's the reason why I think env variables for these values should be deleted so that config will look like that:
```php
    'settings_field_name' => 'settings',
    'settings_table_name' => 'model_settings',
```
Instead of that:
```php
    'settings_field_name' => env('MODEL_SETTINGS_FIELD_NAME', 'settings'),
    'settings_table_name' => env('MODEL_SETTINGS_TABLE_NAME', 'model_settings'),
```

Does it makes sense?

**Comment by hivokas** [comment]
This relates to the `MODEL_SETTINGS_PERSISTENT` as well. I rely on this behavior in the code and don't want the environment variable to change this behavior.

**Comment by glorand** [comment]
@hivokas thanks for the observation, I agree with you and will be updated on the next release.
But if you have time to help me with a PR, ..... :)
