### ISSUE TITLE
Purpose of this settings? 

### ISSUE THREAD

**Issue by eugenevdm** [glorand/laravel-model-settings#7]
I don't get it. What's the real world goal / application of this project? The README doesn't explain what one would use this for.

**Comment by rluders** [comment]
Hello,

So, imagine that in your system you have Users, and a Notification system, that notifies the User about several system events. You can use this package to store the user notification preferences.

**Comment by glorand** [comment]
Specific settings for an entity. Ex. Users model: you want to manage notifications (in app, slack, push notif. etc.),

**Comment by forgottencreature** [comment]
Come to think of it, this could likely be used to support "meta" fields too... information you may want to have about a record but not necessarily stuff you need to have as columns in your table.
