### ISSUE TITLE
[Help] How to eager load settings for all users?

### ISSUE THREAD

**Issue by 77media-creations** [glorand/laravel-model-settings#72]
I recently came across a scenario where I needed settings for all the users in the collection. I tried to eager load it but unfortunately it doesn't work. I am using `HasSettingsTable` trait.

`$users = User::with('settings')->get();`

This returns an error:
`Call to undefined method Glorand\Model\Settings\Managers\TableSettingsManager::addEagerConstraints()`

So I was wondering if there is any way to get this relation eager load?
I have version 3.6.5 installed.

**Comment by glorand** [comment]
@77media-creations 
Please check here the Laravel Documentation:
https://laravel.com/docs/8.x/eloquent-relationships#nested-eager-loading-morphto-relationships

**Comment by firegore2** [comment]
@glorand please, Could you give an example ?

**Comment by szwss** [comment]
I also encountered the same problem, using the beyondcode/laravel-query-detector package, 

when I run: $model->load('settings')->settings()->set('foot.name','test ');

Error: 
```
Call to undefined method Glorand\Model\Settings\Managers\TableSettingsManager::addEagerConstraints(),
```
 but I don’t use ->load('settings’), the page will pop up the N+1 question
