### ISSUE TITLE
[Proposal] Add ability to set connection to HasSettingsTable trait

### ISSUE THREAD

**Issue by EvgeniiaPopova** [glorand/laravel-model-settings#74]
Hey! Nice work on package. 
But I have proposal on future, so we can set connection not only for HasSettingsField trait.

It will be very handy. 

We have different connection through the project and use the HasSettingsTable trait. But we figured it out, about we really miss the ability to set connection (just use model one). Now it's good when you're updating existing settings in the table, but if you try to create new one -- it using default connection name instead of model one

So it's really good feature I think. 

P.S. I will be glad to help you with PR, if you'll approve this proposal

**Comment by glorand** [comment]
@EvgeniiaPopova - thanks for the observation totally agree with your idea. If you have time you can create a PR
