### ISSUE TITLE
Incompatible declaration of Traits\HasSettingsField::settings() error on PHP 8

### ISSUE THREAD

**Issue by alin78hai** [glorand/laravel-model-settings#75]
Hi. After updating to PHP 8.0, I get this exception:

Declaration of Glorand\Model\Settings\Traits\HasSettingsField::settings(): Glorand\Model\Settings\Contracts\SettingsManagerContract must be compatible with Glorand\Model\Settings\Traits\HasSettings::settings(): Glorand\Model\Settings\Managers\AbstractSettingsManager
at ...vendor\glorand\laravel-model-settings\src\Traits\HasSettingsField.php:37

**Comment by glorand** [comment]
@alin78hai I didn't started to test the package on PHP 8, but thx for the observation, probably is the moment to start...

**Comment by SebastianSchoeps** [comment]
Hey, any news on this? It blocks my project from upgrading to PHP 8 (however: just asking! Thanks for your efforts being put in this package - don't wanna pressure!).

Sebastian

**Comment by glorand** [comment]
@SebastianSchoeps thanks! I want to make a new release next week, probably monday.

**Comment by glorand** [comment]
@SebastianSchoeps, @alin78hai  we are PHP8 ready: #79

**Comment by SebastianSchoeps** [comment]
Thank you - great!
