### ISSUE TITLE
I get an error related to Declaration of HasSettingsTable::settings() must be compatible with HasSettings::settings()

### ISSUE THREAD

**Issue by pathros** [glorand/laravel-model-settings#81]
**Problem**
Recently, I modified some notifications, which involve the use of the `HasSettingsTable` trait right at the User.php model.

Now I get the following error every time a notification is triggered:

> Declaration of Glorand\Model\Settings\Traits\HasSettingsTable::settings(): Glorand\Model\Settings\Contracts\SettingsManagerContract must be compatible with Glorand\Model\Settings\Traits\HasSettings::settings(): Glorand\Model\Settings\Managers\AbstractSettingsManager
> 
> at vendor/glorand/laravel-model-settings/src/Traits/HasSettingsTable.php:26
> 
>     22|     /**
>     23|      * @return \Glorand\Model\Settings\Contracts\SettingsManagerContract
>     24|      * @throws \Glorand\Model\Settings\Exceptions\ModelSettingsException
>     25|      */
>   > 26|     public function settings(): SettingsManagerContract
>     27|     {
>     28|         return new TableSettingsManager($this);
>     29|     }
>     30| 
> 

I got the `3.7.0` version of this `glorand/laravel-model-settings` package.

Can anyone shed some light on how to make it work? How do I fix this?

**Comment by glorand** [comment]
Probably you are using PHP 8, please make an upgrade of the package to the latest version 4.*

**Comment by pathros** [comment]
Thanks, Lorand!

You are right, I'd updated Laravel Homestead that now uses PHP 8 as default. So, PHP version should be used with `laravel-model-settings` V3.7.0, and PHP 8 for `laravel-model-settings` V4

In this [StackOverflow answer](https://stackoverflow.com/a/58615463/1883256), it is explained how to quickly switch between PHP versions in Laravel Homestead (for future reference or readers passing by)
