### ISSUE TITLE
Default numeric array values merged after deletion

### ISSUE THREAD

**Issue by edwinvdpol** [glorand/laravel-model-settings#82]
**Describe the bug**
Default numeric array values are being merged after deletion.

**To Reproduce**
1. Define a numeric array as default settings

```php
public $defaultSettings = [
    'presets' => [
        'first',
        'second',
    ],
]
```

2. Add a setting, and save it.

```php
$presets = $model->settings()->get('presets');
$presets[] = 'third';
$model->settings()->set('presets', $presets);

/**
 * Database JSON result:
 * 
 * "presets":[
 *     "first",
 *     "second",
 *     "third"
 *. ],
 */
```

3. Remove "second" from the settings and decode the value:

```php
$model->settings()->delete("presets.1");

/**
 * Database JSON result:
 * 
 * "presets": {
 *     "0":"first",
 *     "2":"third"
 * },
 */

$model->settings()->get('presets');

/**
 * JSON result:
 * 
 * "presets": {
 *     "0":"first",
 *     "1":"second",
 *     "2":"third"
 * },
 */
```

**Expected behavior**
Now, the **default** setting `1` with value `second` is being merged, but it shouldn't exist anymore.

I don't know if this is even possible, but I wanted to ask here before I change to associative array's ;-)

Isn't it possible that if the setting already exists, the defaults aren't being merged anymore?
Or, is there a workaround?

Thanks!

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 88

**Comment by glorand** [comment]
@edwinvdpol Hello, I think the best solution is to use change to associative array's.
