### ISSUE TITLE
Unable to use laravel-model-settings with laraval-spatie-multitenancy

### ISSUE THREAD

**Issue by scramatte** [glorand/laravel-model-settings#86]
**Describe the bug**
I'm unable to use laravel-model-settings with laraval-spatie-multitenancy due to collision  between traits

**To Reproduce**
1. Create a model that use both "HasSettingsField" and "UsesLandlordConnection" or "UsesTenantConnection"
2. Execute seeder
php artisan tenants:artisan "migrate --path=database/seeders/tenant --database=tenant --seed

**Expected behavior**
Seed database without exception

** Actual behavior**

Trait method Glorand\Model\Settings\Traits\HasSettingsField::getConnectionName has not been applied as App\Models\Tenant::getConnectionName, because of collision with Spatie\Multitenancy\Models\Concerns\UsesLandlordConnection::getConnectionName

**Screenshots**
![image](https://user-images.githubusercontent.com/188766/114148658-4c1b7780-991a-11eb-9454-0665850ef449.png)

**Additional context**
https://spatie.be/docs/laravel-multitenancy/v1/introduction

**Comment by glorand** [comment]
You can omit a method's inclusion by excluding it from one trait in favor of the other and doing the exact same thing in the reverse way.
```php
trait A {
    public function sayHello()
    {
        echo 'Hello from A';
    }

    public function sayWorld()
    {
        echo 'World from A';
    }
}

trait B {
    public function sayHello()
    {
        echo 'Hello from B';
    }

    public function sayWorld()
    {
        echo 'World from B';
    }
}

class Talker {
    use A, B {
        A::sayHello insteadof B;
        A::sayWorld insteadof B;
        B::sayWorld insteadof A;
    }
}

$talker = new Talker();
$talker->sayHello();
$talker->sayWorld();
```
The method sayHello is imported, but the method sayWorld is simply excluded.

**Comment by glorand** [comment]
Overriding & Extending a PHP Trait Method
```php
trait FooTrait
{
	public function bar()
	{
		return 'A';
	}
}

class Example
{
	use FooTrait {
		bar as traitBar;
	}

	public function bar()
	{
		return $this->traitBar() . 'B';
	}
}

echo (new Example())->bar(); // Outputs 'AB'
```

Reference: https://andy-carter.com/blog/overriding-extending-a-php-trait-method
