### ISSUE TITLE
[Proposal] Settings validations

### ISSUE THREAD

**Issue by Lukasss93** [glorand/laravel-model-settings#87]
**Is your feature request related to a problem? Please describe.**
This is a proposal to a new feature that could be implemented in this project.

**Describe the solution you'd like**
Add a validation system when you're using the set() or update() methods to throw an exception when you break a rule.

**Describe alternatives you've considered**
You could check the value before set or update a setting but, in my opinion, is long and boring...

**Additional context**
This is an example of how it could be implemented:
```php
class Chat extends Model
{
    use HasSettingsTable;

    public array $defaultSettings = [
        'news' => true,
        'language' => 'en',
        'max_size' => 12,
    ];

    // settings rules
    public array $settingsRules = [
        'news' => 'bool',
        'language' => 'string|in:en,es,it|max:2',
        'max_size' => 'int|min:5|max:15',
    ];
}

// set or update setting
Chat::find(1)->settings()->set('language','it'); // OK!
Chat::find(1)->settings()->set('news',123456); // throws an exception! - it must be a boolean

```

**Comment by glorand** [comment]
@Lukasss93 Hello, thank you for your proposal. I think will be delivered in the next release

**Comment by Lukasss93** [comment]
Wrong phpdoc?
![immagine](https://user-images.githubusercontent.com/4071613/141001822-f53eb774-e83a-4545-9876-bcaeafdcc8eb.png)


You can't use custom rules...
![immagine](https://user-images.githubusercontent.com/4071613/141001871-95d6659e-2495-4532-b6e3-34239146c17a.png)

**Comment by glorand** [comment]
@Lukasss93 thank you for your observation, will be fixed asap!

**Comment by glorand** [comment]
PR: #95

**Comment by rensphilipsen** [comment]
Does this somehow try to use the "default" model rules as fallback? I have one value (lets say a "name" value) that should not be saved in the settings which has a validation rule and it tries to validate if "name" is in the settings model. I do not want it to be saved in the settings model but it doesn't let me create the settings model without adding the "name" value.

Thanks for the package! :)
