### ISSUE TITLE
Can't search for settings via a model.

### ISSUE THREAD

**Issue by kevinruscoe** [glorand/laravel-model-settings#9]
I'm using the table based setup, and I have a User model that has a setting named `nickname`.

Searching via a setting field blows up.

```
$user->with([
    'settings' => function($builder) use ($nickname) {
        $builder->where('nickname', $nickname);
    }
]);
```

Throws a `Call to undefined method Glorand\Model\Settings\Managers\TableSettingsManager::addEagerConstraints()` exception.

**Comment by glorand** [comment]
@kevinruscoe us with `MorphOne'
```php
$testData = User::with(['modelSettings' => function (MorphOne $builder) {
    $builder->where(DB::raw("json_extract(settings, '$.user.first_name')"), 'John');
}])
```

**Comment by hubertnnn** [comment]
I think adding an explicit filter to the library would be beneficial, so we could do something like:
`$emails => User::withSettings('newsletter', true)->pluck('email')`

**Comment by glorand** [comment]
> I think adding an explicit filter to the library would be beneficial, so we could do something like:
> `$emails => User::withSettings('newsletter', true)->pluck('email')`
@hubertnnn Thanks for the comment; already have the filter functionality on the roadmap, will create a dedicated card in the project section.

**Comment by limsocheat** [comment]
> I think adding an explicit filter to the library would be beneficial, so we could do something like:
> `$emails => User::withSettings('newsletter', true)->pluck('email')`

how to filter it now? 
currently, I use 

```
$testData = User::with(['modelSettings' => function (MorphOne $builder) {
    $builder->where(DB::raw("json_extract(settings, '$.user.first_name')"), 'John');
}])
```

but it is not effected at all.

**Comment by cthom-dev** [comment]
For those that need it

```User::whereHas('modelSettings', function ($query) {
        $query->where('settings->user->age', '33');
    })->get();```
