### ISSUE TITLE
Declaration of Glorand\Model\Settings\Traits\HasSettingsField::settings(): Glorand\Model\Settings\Contracts\SettingsManagerContract must be compatible with Glorand\Model\Settings\Traits\HasSettings::settings(): Glorand \Model\Settings\Managers\AbstractSettingsManager

### ISSUE THREAD

**Issue by mohammad425** [glorand/laravel-model-settings#91]
my PHP version => 8.0, Laravel version => 8.53.1, laravel-model-settings package version => 4.2.2

i added `Glorand\Model\Settings\Traits\HasSettingsField` to my model and when run `php artisan migrate` get the error:

`Declaration of Glorand\Model\Settings\Traits\HasSettingsField::settings(): Glorand\Model\Settings\Contracts\SettingsManagerContract must be compatible with Glorand\Model\Settings\Traits\HasSettings::settings(): Glorand \Model\Settings\Managers\AbstractSettingsManager`

![image](https://user-images.githubusercontent.com/12151806/128542291-3266f01d-1024-4298-81d8-d199a886ca26.png)

**Comment by pathros** [comment]
`composer require glorand/laravel-model-settings:4.4.1` worked for me. Thank you.
