### ISSUE TITLE
No support to custom validation rules

### ISSUE THREAD

**Issue by Lukasss93** [glorand/laravel-model-settings#96]
**Describe the bug**
There is no support to add custom validation rules
Reference: https://github.com/glorand/laravel-model-settings/issues/87#issuecomment-964529183

**To Reproduce**
Add a custom validation rule. You'll get "expression is not allowed as field default value".

**Expected behavior**
Convert the "settingsRules" property to a method like the "rules" method in Laravel FormRequest

**Screenshots**
![141001871-95d6659e-2495-4532-b6e3-34239146c17a](https://user-images.githubusercontent.com/4071613/145727239-c2fd51d6-7c78-4fb4-a194-857f011f6852.png)

**Comment by Lukasss93** [comment]
😥

**Comment by Lukasss93** [comment]
The project seems to be abandoned.
I am closing the issue because [I have forked this project](https://github.com/Lukasss93/laravel-model-settings), fixed this issue, and also added other features.

**Comment by glorand** [comment]
@Lukasss93 sorry for late answer. Can you make a pull request for this feature. Thanks in advance!
